### ISSUE TITLE
RUSTSEC-2020-0159 - Potential segfault in localtime_r invocations

### ISSUE THREAD

**Issue by fmorency** [Nullus157/cbor-diag-rs#119]
Affects `chrono` < 0.4.20

See https://rustsec.org/advisories/RUSTSEC-2020-0159

**Comment by Nemo157** [comment]
The library's dependency version requirement allows for users to use a fixed version. The CLI is unaffected because it is single-threaded.

**Comment by Nemo157** [comment]
(It probably is still worth bumping the minimum requirement to a fixed one though).

**Comment by fmorency** [comment]
> (It probably is still worth bumping the minimum requirement to a fixed one though).

Yes! `cargo audit` will complain otherwise.

**Comment by Nemo157** [comment]
I just published `cbor-diag` 0.1.10 which bumps the minimum supported `chrono` version to 0.4.22.
