### ISSUE TITLE
Compile error when installing cbor-diag-cli

### ISSUE THREAD

**Issue by inf265** [Nullus157/cbor-diag-rs#128]
Hi,
I am new to rust but want to use the cbor-diag-cli. When using the cargo command to install I get a buch of errors of the same category:
```   Compiling textwrap v0.15.1
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
   --> /home/fmetz/.cargo/registry/src/github.com-1ecc6299db9ec823/cbor-diag-0.1.11/src/encode/hex.rs:506:27
    |
506 |             typed_array::<1>(context, value, "unsigned", |[byte]| byte.to_string())
    |                           ^ explicit generic argument not allowed
    |
    = note: see issue #83701 <https://github.com/rust-lang/rust/issues/83701> for more information

```
Any help ?
Best Regards
Fréd

**Comment by Nemo157** [comment]
It looks like you're using an outdated compiler, that was [stabilized in 1.63](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#turbofish-for-generics-in-functions-with-impl-trait). You can updated with `rustup update` (or, if you're using the system rust on a distro like Debian that does not ship up-to-date compilers you'll [have to install `rustup`](https://www.rust-lang.org/tools/install)).

**Comment by inf265** [comment]
Thanks great I was on 1.59, updated to 1.6x and now it runs. Thank you.
