### ISSUE TITLE
Update from nom 5

### ISSUE THREAD

**Issue by chrysn** [Nullus157/cbor-diag-rs#134]
Building nom with a recent Rust raises warnings about future compatibility:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
```

It appears that nom uses some macro syntax that was only accidentally valid.

I just briefly tried bumping the nom version to 7, but while I could do the change from separated_list to separated_list0 easily (nom 6's changelog says it was effectively renamed), other errors seem to require understanding what it does, for which unfortunately I don't have the time right now.

**Comment by Nemo157** [comment]
Turns out I had an old update branch I forgot about <https://github.com/Nullus157/cbor-diag-rs/compare/pr%C4%ABmum...Nemo157:cbor-diag-rs:nom-7>, hopefully it was just waiting on that fix for over-allocation and I can get it merged soon.

**Comment by fmorency** [comment]
Friendly bump! :)

**Comment by Nemo157** [comment]
Just publish 0.1.12 with nom 7.
